#!/bin/sh
ROOT=$(cd $(dirname $0);cd ../ && pwd)
TEST_FILE=$(dirname $0)"/test.js"
while true
do
    echo '----'
    node ${TEST_FILE}
    # rm -r ${ROOT}/compile/*
    # find ${ROOT}/ -type d -name "node_modules" -prune -o -type f -name '*.ts' -print\
        # | xargs tsc --out ${ROOT}/compile/ \
        # && node ${TEST_FILE}
    inotifywait -r -e modify --exclude '.*\.sw.' ${ROOT} --quiet
done
